### ISSUE TITLE
error deploy to netlify 

### ISSUE THREAD

**Issue by jesushernandez55** [rokhimin/blog#1]
I'm can't deploy to netlify .
message error "not found"

**Comment by rokhimin** [comment]
right , netlify can't instant deploy from branch beside "master"
I use branch "deploy_netlify"
https://app.netlify.com/start/deploy?repository=https://github.com/rokhimin/blog/tree/deploy_netlify

**Comment by rokhimin** [comment]
You can clone/download branch "deploy_netlify" 
https://github.com/rokhimin/blog/tree/deploy_netlify 
.
and push to new your repos .
fools , click instant deploy
https://app.netlify.com/start/deploy?repository=https://github.com/jesushernandez55/*NameRepos*

**Comment by rokhimin** [comment]
don't close this issue , wait netlify fixed okay :)
